name = "topcat-model-category"
version = "0.1.0"
defaultTargets = ["TopCatModelCategory"]

[[lean_lib]]
name = "TopCatModelCategory"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "6c193806481aaf608f1396601b6dc95277ddcfe8"

